[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
burn = "burnpzY5Sy2j4ZyQmjdQbBFiJW9T99GxDykASG2QrMu"
fee_distributor = "burnfZzJfuR8b8yMRGgZfLAq7P2eCuMdRgGooQjPjua"
hooks = "burnhzSCeNMFuTsQJRC8dc1EPffWAecnYk8CxxRuQzT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
deploy-burn = "ts-node -P ./tsconfig.json scripts/deploy-burn.ts"
deploy-fee-distributor = "ts-node -P ./tsconfig.json scripts/deploy-fee-distributor.ts"
initialize-market = "ts-node -P ./tsconfig.json scripts/initialize-market.ts"
buy-and-sell-token = "ts-node -P ./tsconfig.json scripts/buy-and-sell-token.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts tests/**/*.ts"
test-math = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/math/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
